---
- hosts: "{{hosts}}"
  gather_facts: False
  vars: 
     - service: sshd
  tasks:
       - name: Checking Service status
         win_shell: get-service -name {{service}}
         register: result
       - name: showing status
         debug: 
          msg: "{{result.stdout_lines}}"